<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-VT80RB39" ignored="0" name="RetryMultipleTestCases" tests="9" failures="2" timestamp="2020-04-15T12:06:02 IST" time="0.072" errors="0">
  <testcase name="Test1" time="0.011" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="mytests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test1(MyTests.java:11)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="mytests.MyTests"/>
  <testcase name="Test3" time="0.001" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.001" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.0" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.001" classname="mytests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test3(MyTests.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
</testsuite> <!-- RetryMultipleTestCases -->
